global:
  scrape_interval: 15s  

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['web:5000']

  - job_name: 'fastapi_app'
    static_configs:
      - targets: ['fastapi-app:8000'] 

  - job_name: 'redis'
    scrape_interval: 30s
    static_configs:
      - targets: ['redis-exporter:9121']  

  - job_name: 'elasticsearch'
    scrape_interval: 30s
    static_configs:
      - targets: ['elasticsearch-exporter:9114']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
