global:
  scrape_interval: 15s  

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['web:5000']
    tls_config:
      insecure_skip_verify: true


  - job_name: 'fastapi_app'
    static_configs:
      - targets: ['fastapi-app:8000'] 

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']  

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200'] 

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 

